package com.example.bsproperty.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.bsproperty.bean.TypeBean;
import com.example.bsproperty.bean.AccBean;
import com.example.bsproperty.bean.NewBean;

import com.example.bsproperty.bean.TypeBeanDao;
import com.example.bsproperty.bean.AccBeanDao;
import com.example.bsproperty.bean.NewBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig typeBeanDaoConfig;
    private final DaoConfig accBeanDaoConfig;
    private final DaoConfig newBeanDaoConfig;

    private final TypeBeanDao typeBeanDao;
    private final AccBeanDao accBeanDao;
    private final NewBeanDao newBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        typeBeanDaoConfig = daoConfigMap.get(TypeBeanDao.class).clone();
        typeBeanDaoConfig.initIdentityScope(type);

        accBeanDaoConfig = daoConfigMap.get(AccBeanDao.class).clone();
        accBeanDaoConfig.initIdentityScope(type);

        newBeanDaoConfig = daoConfigMap.get(NewBeanDao.class).clone();
        newBeanDaoConfig.initIdentityScope(type);

        typeBeanDao = new TypeBeanDao(typeBeanDaoConfig, this);
        accBeanDao = new AccBeanDao(accBeanDaoConfig, this);
        newBeanDao = new NewBeanDao(newBeanDaoConfig, this);

        registerDao(TypeBean.class, typeBeanDao);
        registerDao(AccBean.class, accBeanDao);
        registerDao(NewBean.class, newBeanDao);
    }
    
    public void clear() {
        typeBeanDaoConfig.clearIdentityScope();
        accBeanDaoConfig.clearIdentityScope();
        newBeanDaoConfig.clearIdentityScope();
    }

    public TypeBeanDao getTypeBeanDao() {
        return typeBeanDao;
    }

    public AccBeanDao getAccBeanDao() {
        return accBeanDao;
    }

    public NewBeanDao getNewBeanDao() {
        return newBeanDao;
    }

}
